#---------------------------
# 全局
# Global
#---------------------------

#  自定义页面灰色配置
# 详情查看 https://github.com/yxlazy/blog/blob/master/themes/fluid/source/js/grayscale.js
grayscale: false

# 用于浏览器标签的图标
# Icon for browser tab
favicon: /img/avatar.jpg

# 网页访问统计
# Analysis of website visitors
web_analytics:  # 网页访问统计
  enable: true

  # 百度统计的 Key，值需要获取下方链接中 `hm.js?` 后边的字符串
  # Baidu analytics, get the string behind `hm.js?`
  # See: https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376
  baidu: 8514c4ed7d7682442371b277e8bfea43

#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
  # Navigation bar frosted glass special animation. It is an experimental feature
  ground_glass:
    enable: true

# 搜索功能，基于 hexo-generator-search 插件，若已安装其他搜索插件请关闭此功能，以避免生成多余的索引文件
# Search feature, based on hexo-generator-search. If you have installed other search plugins, please disable this feature to avoid generating redundant index files
search:

  # 搜索的范围
  # Search field
  # Options: post | page | all
  field: all

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 展示网站的 PV、UV 统计数
  # Display website PV and UV statistics
  statistics:
    enable: true

#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/home-background.jpg

#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/post-background.jpg

  # 文章标题下方的元信息
  # Meta information below title
  meta:
    # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
    # Author, based on `author` field in front-matter, if not set, based on `author` value in hexo config
    author:
      enable: true
    # 浏览量计数
    # Number of visits
    views:
      enable: true

  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  # Update date is displayed at the beginning of the post. The default date is the update date of the md file, which can be manually specified by `updated` in front-matter (same format as date)
  updated:
    enable: true

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/archive-background.jpg

#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: /img/category-background.jpg

#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/tag-background.jpg

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/about-background.jpg
  avatar: /img/avatar.jpg
  name: "yxlazy"
  intro: "A front-end developer who likes to explore"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/yxlazy", tip: "GitHub" }
    - { class: "iconfont icon-zhihu-fill", link: "https://www.zhihu.com/people/ren-sheng-ji-he-95-52", tip: "知乎" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/gongzhonghao.bmp" }